server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/common_test_app?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    persistAuthorization: true
    display-request-duration: true
    operations-sorter: method
    doc-expansion: none

# ←←← SendGrid キーが「空」だと MailService は “送信せずログ出力” に切り替えます
sendgrid:
  apiKey: ""

app:
  mail:
    from: "no-reply@common-test-app.local"
  # 検証URLのベース（バックエンドの公開URL）。Heroku 乗せ替え時に差し替え予定
  backendBaseUrl: "http://localhost:8080"
