server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/common_test_app?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true   # ← petstore 無効化（超重要）
    url: /v3/api-docs                    # ← これを明示
    config-url: /v3/api-docs/swagger-config
    try-it-out-enabled: true
    persist-authorization: true
    display-request-duration: true




jwt:
  secret: "QkR0dGJrZ0p5c0o3cU1kV1Z2c1ZqV2ZrQ0pYTlR2M0l5cU1MN29kT1hYZ3ZHS2JXbGZFM1lxc1BOWk1SVGc9PQ=="
  expiration-ms: 2592000000
